services:
  db_mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: db_mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_APP_DB: ${MONGO_APP_DB}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval \"db.getSiblingDB('blog_db').posts.countDocuments()\" | grep 5 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute=\"SELECT COUNT(*) FROM ynov_ci.utilisateur HAVING COUNT(*) = 4;\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  admin_mongo:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: admin_mongo
    restart: on-failure
    depends_on:
      db_mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db_mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"

  admin_mysql:
    image: adminer
    container_name: admin_mysql
    restart: on-failure
    depends_on:
      db_mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    depends_on:
      db_mongo:
        condition: service_healthy
      db_mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: db_mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MONGO_HOST: db_mongo
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_APP_USER}
      MONGO_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_DB: ${MONGO_APP_DB}
    volumes:
      - ./api/main.py:/app/main.py
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/health | grep '\"status\":\"healthy\"' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s